import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";
import FirstNavbar from "@/component/FirstNavbar";
import { Toaster } from 'react-hot-toast';
import Provider from "@/component/provider/Provider";
import CardContextProvider from '@/context/cardContext'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="max-h-full flex flex-col ">
      <CardContextProvider>
       <Provider>
         <FirstNavbar/>
        <Navbar/>
        {children}
         <Toaster />
        <Footer/>
       </Provider>
       </CardContextProvider>
        </body>
    </html>
  );
}
